# Generated by Django 5.2.17 on 2026-08-07 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('lessons', '0003_delete_lessonprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'course progress',
                'verbose_name_plural': 'course progress',
                'constraints': [models.UniqueConstraint(fields=('user', 'course'), name='progress_course_unique')],
            },
        ),
        migrations.CreateModel(
            name='LearningActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_date', models.DateField()),
                ('activity_type', models.CharField(choices=[('lesson_completed', 'Lesson completed'), ('quiz_completed', 'Quiz completed'), ('recipe_created', 'Recipe created')], max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_activity', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'learning activity',
                'verbose_name_plural': 'learning activity',
                'ordering': ('-activity_date', '-id'),
                'indexes': [models.Index(fields=['user', '-activity_date'], name='progress_activity_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'activity_date', 'activity_type'), name='progress_activity_unique')],
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('first_completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_viewed_at', models.DateTimeField(blank=True, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='lessons.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'lesson progress',
                'verbose_name_plural': 'lesson progress',
                'indexes': [models.Index(fields=['user', 'completed_at'], name='progress_lesson_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'lesson'), name='progress_lesson_unique')],
            },
        ),
    ]
