# Generated by Django 5.2.17 on 2026-08-08 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('recipes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField(max_length=4000)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_answers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'answer',
                'verbose_name_plural': 'answers',
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='QuestionThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True, max_length=4000)),
                ('status', models.CharField(choices=[('active', 'Active'), ('hidden', 'Hidden by moderation'), ('deleted', 'Deleted by the author')], db_index=True, default='active', max_length=20)),
                ('accepted_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_for', to='qa.questionanswer')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_threads', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_threads', to='courses.course')),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_threads', to='recipes.recipe')),
            ],
            options={
                'verbose_name': 'question thread',
                'verbose_name_plural': 'question threads',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='qa.questionthread'),
        ),
        migrations.AddIndex(
            model_name='questionthread',
            index=models.Index(fields=['status', '-created_at'], name='qa_thread_feed_idx'),
        ),
        migrations.AddIndex(
            model_name='questionthread',
            index=models.Index(fields=['recipe', 'status', '-created_at'], name='qa_thread_recipe_idx'),
        ),
        migrations.AddIndex(
            model_name='questionthread',
            index=models.Index(fields=['course', 'status', '-created_at'], name='qa_thread_course_idx'),
        ),
        migrations.AddConstraint(
            model_name='questionthread',
            constraint=models.CheckConstraint(condition=models.Q(('course__isnull', False), ('recipe__isnull', False), _negated=True), name='qa_at_most_one_target'),
        ),
        migrations.AddIndex(
            model_name='questionanswer',
            index=models.Index(fields=['thread', 'created_at'], name='qa_answer_thread_idx'),
        ),
    ]
