# Generated by Django 5.2.17 on 2026-08-11 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreadView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='qa.questionthread')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'thread view',
                'verbose_name_plural': 'thread views',
                'ordering': ('-created_at', '-id'),
                'constraints': [models.UniqueConstraint(fields=('thread', 'user'), name='qa_one_view_per_reader')],
            },
        ),
    ]
