# Generated by Django 5.2.17 on 2026-08-10 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('terms', 'Terms of service'), ('privacy', 'Privacy policy'), ('pdpa', 'PDPA notice'), ('cookie', 'Cookie policy')], max_length=20, unique=True)),
                ('title', models.CharField(max_length=120)),
                ('body', models.TextField()),
                ('version', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'legal document',
                'verbose_name_plural': 'legal documents',
                'ordering': ('kind',),
            },
        ),
    ]
