# Generated by Django 5.2.17 on 2026-08-07 15:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title_th', models.CharField(max_length=100)),
                ('title_en', models.CharField(max_length=100)),
                ('description_th', models.CharField(blank=True, max_length=255)),
                ('description_en', models.CharField(blank=True, max_length=255)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'badge definition',
                'verbose_name_plural': 'badge definitions',
                'ordering': ('slug',),
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_type', models.CharField(choices=[('course_completed', 'Completed a course'), ('first_course', 'First course completed'), ('ten_courses', 'Ten courses completed'), ('quiz_master', 'Quiz master'), ('recipe_author', 'Recipe author')], max_length=30)),
                ('awarded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
                ('badge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='achievements', to='certificates.badgedefinition')),
            ],
            options={
                'verbose_name': 'achievement',
                'verbose_name_plural': 'achievements',
                'ordering': ('-awarded_at', '-id'),
                'constraints': [models.UniqueConstraint(fields=('user', 'achievement_type'), name='certificates_one_per_type')],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('certificate_number', models.CharField(max_length=20, unique=True)),
                ('verification_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('issued_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('student_name', models.CharField(max_length=150)),
                ('course_title', models.CharField(max_length=200)),
                ('completed_at', models.DateTimeField()),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'certificate',
                'verbose_name_plural': 'certificates',
                'ordering': ('-issued_at', '-id'),
                'indexes': [models.Index(fields=['user', '-issued_at'], name='cert_user_issued_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True)), fields=('user', 'course'), name='certificates_one_active_per_course')],
            },
        ),
    ]
