# Generated by Django 5.2.17 on 2026-08-11 02:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0004_certificate_revoked_by_certificate_revoked_reason'),
        ('courses', '0002_course_published_duration_minutes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('draft_design', models.JSONField()),
                ('published_design', models.JSONField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_template', to='courses.course')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificate_templates_edited', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'certificate template',
                'verbose_name_plural': 'certificate templates',
                'ordering': ('-updated_at', '-id'),
            },
        ),
    ]
