# Generated by Django 5.2.17 on 2026-08-09 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('honeypot_path', 'Requested a trap path'), ('sensitive_file_probe', 'Probed for a secret file'), ('path_traversal', 'Path traversal attempt'), ('sqli_probe', 'SQL injection probe'), ('xss_probe', 'Cross-site scripting probe'), ('scanner_agent', 'Known attack tool user agent'), ('automation_agent', 'Scripted client (curl, requests…)'), ('missing_user_agent', 'No user agent supplied'), ('not_found_sweep', 'Burst of 404s (content sweep)'), ('auth_failure_burst', 'Burst of rejected requests'), ('request_flood', 'Request rate far above normal'), ('devtools_opened', 'Browser devtools appear to be open'), ('view_source_attempt', 'View-source shortcut pressed'), ('context_menu_attempt', 'Context menu suppressed'), ('console_tamper', 'Console/debugger tampering detected')], db_index=True, max_length=32)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, max_length=10)),
                ('score_delta', models.FloatField(help_text="Points this observation added to the offender's score.")),
                ('ip', models.GenericIPAddressField(db_index=True)),
                ('user_agent', models.CharField(blank=True, max_length=400)),
                ('path', models.CharField(blank=True, max_length=400)),
                ('method', models.CharField(blank=True, max_length=10)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('request_id', models.CharField(blank=True, max_length=40)),
                ('detail', models.JSONField(blank=True, default=dict, help_text='Detector-specific context, e.g. the marker that matched.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'security event',
                'verbose_name_plural': 'security events',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['ip', '-created_at'], name='sec_event_ip_idx'), models.Index(fields=['kind', '-created_at'], name='sec_event_kind_idx')],
            },
        ),
        migrations.CreateModel(
            name='ThreatProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(unique=True)),
                ('score', models.FloatField(default=0.0)),
                ('level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='low', max_length=10)),
                ('event_count', models.PositiveIntegerField(default=0)),
                ('last_kind', models.CharField(blank=True, choices=[('honeypot_path', 'Requested a trap path'), ('sensitive_file_probe', 'Probed for a secret file'), ('path_traversal', 'Path traversal attempt'), ('sqli_probe', 'SQL injection probe'), ('xss_probe', 'Cross-site scripting probe'), ('scanner_agent', 'Known attack tool user agent'), ('automation_agent', 'Scripted client (curl, requests…)'), ('missing_user_agent', 'No user agent supplied'), ('not_found_sweep', 'Burst of 404s (content sweep)'), ('auth_failure_burst', 'Burst of rejected requests'), ('request_flood', 'Request rate far above normal'), ('devtools_opened', 'Browser devtools appear to be open'), ('view_source_attempt', 'View-source shortcut pressed'), ('context_menu_attempt', 'Context menu suppressed'), ('console_tamper', 'Console/debugger tampering detected')], max_length=32)),
                ('last_path', models.CharField(blank=True, max_length=400)),
                ('last_user_agent', models.CharField(blank=True, max_length=400)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(db_index=True)),
                ('blocked_until', models.DateTimeField(blank=True, null=True)),
                ('review_state', models.CharField(choices=[('open', 'Needs review'), ('acknowledged', 'Reviewed — watching'), ('ignored', 'Reviewed — benign')], db_index=True, default='open', max_length=14)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('blocked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_blocks_issued', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'threat profile',
                'verbose_name_plural': 'threat profiles',
                'ordering': ('-score', '-last_seen_at'),
                'indexes': [models.Index(fields=['-score'], name='sec_profile_score_idx'), models.Index(fields=['level', '-last_seen_at'], name='sec_profile_level_idx')],
            },
        ),
    ]
