# Generated by Django 5.2.17 on 2026-08-07 10:09

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(allow_unicode=True, max_length=80, unique=True)),
            ],
            options={
                'verbose_name': 'question tag',
                'verbose_name_plural': 'question tags',
                'ordering': ('name',),
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='questions_tag_name_ci_unique')],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_type', models.CharField(choices=[('single_choice', 'Single choice'), ('multiple_choice', 'Multiple choice'), ('true_false', 'True / False')], db_index=True, max_length=20)),
                ('text', models.TextField(max_length=1000)),
                ('explanation', models.TextField(blank=True, help_text='Shown to the learner after submitting. A learning aid, not part of what is asked or graded — editable even when frozen.', max_length=2000)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], db_index=True, default='medium', max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('frozen_at', models.DateTimeField(blank=True, help_text='Stamped once when the question is first answered in an attempt; never cleared. Content is immutable from then on.', null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL)),
                ('supersedes', models.ForeignKey(blank=True, help_text='The earlier version this question replaces, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='questions.question')),
                ('tags', models.ManyToManyField(blank=True, related_name='questions', to='questions.questiontag')),
            ],
            options={
                'verbose_name': 'question',
                'verbose_name_plural': 'questions',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='AnswerChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=300)),
                ('is_correct', models.BooleanField(default=False)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='questions.question')),
            ],
            options={
                'verbose_name': 'answer choice',
                'verbose_name_plural': 'answer choices',
                'ordering': ('position', 'id'),
                'indexes': [models.Index(fields=['question', 'position'], name='questions_choice_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['author', 'question_type'], name='questions_author_type_idx'),
        ),
    ]
