# Generated by Django 5.2.17 on 2026-08-07 07:08

import apps.courses.models.course
import django.db.models.deletion
import django.db.models.functions.text
import infrastructure.storage.base
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipe_categories', '0002_seed_from_baking_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(allow_unicode=True, help_text='Frozen once the course is first published.', max_length=180, unique=True)),
                ('summary', models.CharField(blank=True, help_text='One-line description shown on cards.', max_length=300)),
                ('description', models.TextField(blank=True)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('visibility', models.CharField(choices=[('public', 'Anyone'), ('unlisted', 'Anyone with the link'), ('private', 'Only me')], db_index=True, default='public', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('thumbnail', models.ImageField(blank=True, storage=infrastructure.storage.base.get_media_storage, upload_to=apps.courses.models.course.thumbnail_upload_to)),
                ('published_lesson_count', models.PositiveIntegerField(default=0, help_text='Maintained by the lessons app on every lesson mutation. Rebuild with `manage.py recount_lessons`.')),
                ('categories', models.ManyToManyField(blank=True, related_name='courses', to='recipe_categories.recipecategory')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_taught', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'courses',
                'ordering': ('-published_at', '-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('dropped', 'Dropped')], db_index=True, default='active', max_length=20)),
                ('enrolled_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'enrollment',
                'verbose_name_plural': 'enrollments',
                'ordering': ('-enrolled_at', '-id'),
            },
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['status', 'visibility', '-published_at'], name='courses_listing_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['instructor', 'status'], name='courses_instructor_idx'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('slug'), name='courses_course_slug_ci_unique'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['user', 'status'], name='courses_enroll_user_idx'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('user', 'course'), name='courses_enrollment_unique'),
        ),
    ]
