# Generated by Django 5.2.17 on 2026-08-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='published_duration_minutes',
            field=models.PositiveIntegerField(default=0, help_text="Sum of published lessons' durations. Maintained by the lessons app on every lesson mutation; rebuild with `manage.py recount_lessons`."),
        ),
        migrations.AddField(
            model_name='course',
            name='rating_average',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Average of active reviews; null when unreviewed.', max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='rating_count',
            field=models.PositiveIntegerField(default=0, help_text='Count of active reviews.'),
        ),
    ]
