# Generated by Django 5.2.17 on 2026-08-07 03:27

import apps.users.models.profile
import apps.users.validators.user_validator
import django.db.models.deletion
import django.db.models.functions.text
import infrastructure.storage.base
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(help_text='Used to sign in. Stored lowercased.', max_length=254, unique=True, verbose_name='email address')),
                ('username', models.SlugField(help_text='Public handle used in profile URLs.', max_length=30, unique=True, validators=[apps.users.validators.user_validator.validate_username])),
                ('is_active', models.BooleanField(default=True, help_text='Authentication kill-switch. Unset to disable sign-in and invalidate live sessions. Unrelated to email verification.')),
                ('is_staff', models.BooleanField(default=False, help_text='Whether the user may sign in to the Django admin.')),
                ('is_email_verified', models.BooleanField(default=False, help_text='Whether the user has confirmed ownership of their email address.')),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('display_name', models.CharField(blank=True, max_length=60)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('avatar', models.ImageField(blank=True, storage=infrastructure.storage.base.get_media_storage, upload_to=apps.users.models.profile.avatar_upload_to)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('experience_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('professional', 'Professional')], default='beginner', max_length=20)),
                ('favorite_categories', models.JSONField(blank=True, default=list)),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'profiles',
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='preference', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profile_visibility', models.CharField(choices=[('public', 'Anyone'), ('members', 'Signed-in members'), ('private', 'Only me')], default='public', max_length=20)),
                ('show_birthday', models.BooleanField(default=False)),
                ('show_location', models.BooleanField(default=True)),
                ('preferred_difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('professional', 'Professional')], default='beginner', max_length=20)),
                ('weekly_goal_minutes', models.PositiveIntegerField(default=60)),
                ('dietary_restrictions', models.JSONField(blank=True, default=list)),
                ('theme', models.CharField(choices=[('system', 'Match system'), ('light', 'Light'), ('dark', 'Dark')], default='system', max_length=20)),
                ('locale', models.CharField(default='en-us', max_length=10)),
                ('email_course_updates', models.BooleanField(default=True)),
                ('email_product_updates', models.BooleanField(default=True)),
                ('email_marketing', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'user preference',
                'verbose_name_plural': 'user preferences',
            },
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='users_user_email_ci_unique'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('username'), name='users_user_username_ci_unique'),
        ),
    ]
