# Generated by Django 5.2.17 on 2026-08-10 04:11

import apps.users.models.profile
import infrastructure.storage.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_favorite_categories_m2m_and_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cover',
            field=models.ImageField(blank=True, storage=infrastructure.storage.base.get_media_storage, upload_to=apps.users.models.profile.cover_upload_to),
        ),
    ]
