# Generated by Django 5.2.17 on 2026-08-08 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardAccount',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='reward_account', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('balance', models.PositiveIntegerField(default=0)),
                ('lifetime_earned', models.PositiveIntegerField(default=0)),
                ('lifetime_spent', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'reward account',
                'verbose_name_plural': 'reward accounts',
            },
        ),
        migrations.CreateModel(
            name='RewardTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('earn', 'Earn'), ('spend', 'Spend'), ('adjustment', 'Staff adjustment')], max_length=20)),
                ('amount', models.IntegerField(help_text='Signed: positive credits the balance, negative debits it.')),
                ('balance_after', models.PositiveIntegerField()),
                ('reason_code', models.CharField(choices=[('lesson_completed', 'Lesson completed'), ('course_completed', 'Course completed'), ('quiz_completed', 'Quiz completed'), ('certificate_issued', 'Certificate issued'), ('achievement_earned', 'Achievement earned'), ('reward_spent', 'Rewards spent'), ('staff_adjustment', 'Staff adjustment')], max_length=40)),
                ('event_key', models.CharField(max_length=100)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('actor_handle', models.CharField(blank=True, max_length=150)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='rewards.rewardaccount')),
            ],
            options={
                'verbose_name': 'reward transaction',
                'verbose_name_plural': 'reward transactions',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['account', '-created_at'], name='rewards_history_idx')],
                'constraints': [models.UniqueConstraint(fields=('account', 'event_key'), name='rewards_event_once'), models.CheckConstraint(condition=models.Q(('amount', 0), _negated=True), name='rewards_amount_nonzero')],
            },
        ),
    ]
