# Generated by Django 5.2.17 on 2026-08-07 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('lessons', '0003_delete_lessonprogress'),
        ('recipes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('language', models.CharField(choices=[('th', 'Thai'), ('en', 'English')], default='th', max_length=5)),
                ('context_type', models.CharField(choices=[('recipe', 'Recipe'), ('lesson', 'Lesson'), ('course', 'Course'), ('general', 'General')], default='general', max_length=20)),
                ('prompt_version', models.CharField(max_length=20)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_conversations', to='courses.course')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_conversations', to='lessons.lesson')),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_conversations', to='recipes.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'assistant conversation',
                'verbose_name_plural': 'assistant conversations',
                'ordering': ('-updated_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='AssistantMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('system', 'System'), ('user', 'User'), ('assistant', 'Assistant')], max_length=10)),
                ('content', models.TextField()),
                ('provider', models.CharField(blank=True, max_length=32)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('token_input', models.PositiveIntegerField(blank=True, null=True)),
                ('token_output', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='assistant.assistantconversation')),
            ],
            options={
                'verbose_name': 'assistant message',
                'verbose_name_plural': 'assistant messages',
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('language', models.CharField(choices=[('th', 'Thai'), ('en', 'English')], max_length=5)),
                ('version', models.CharField(max_length=20)),
                ('template', models.TextField()),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'prompt template',
                'verbose_name_plural': 'prompt templates',
                'ordering': ('name', 'language', '-created_at'),
                'constraints': [models.UniqueConstraint(fields=('name', 'language', 'version'), name='assistant_prompt_version_unique'), models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('name', 'language'), name='assistant_prompt_one_active')],
            },
        ),
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=32)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI usage log',
                'verbose_name_plural': 'AI usage logs',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['user', '-created_at'], name='assistant_usage_user_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='assistantconversation',
            index=models.Index(fields=['user', '-updated_at'], name='assistant_conv_user_idx'),
        ),
        migrations.AddConstraint(
            model_name='assistantconversation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('context_type', 'recipe'), ('course__isnull', True), ('lesson__isnull', True)), models.Q(('context_type', 'lesson'), ('course__isnull', True), ('recipe__isnull', True)), models.Q(('context_type', 'course'), ('lesson__isnull', True), ('recipe__isnull', True)), models.Q(('context_type', 'general'), ('course__isnull', True), ('lesson__isnull', True), ('recipe__isnull', True)), _connector='OR'), name='assistant_context_matches_type'),
        ),
        migrations.AddIndex(
            model_name='assistantmessage',
            index=models.Index(fields=['conversation', 'created_at'], name='assistant_msg_conv_idx'),
        ),
    ]
