# Generated by Django 5.2.17 on 2026-08-08 05:57

import apps.gallery.models.image
import django.db.models.deletion
import infrastructure.storage.base
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('recipes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caption', models.TextField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('published', 'Published'), ('unpublished', 'Unpublished')], db_index=True, default='published', max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_posts', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_posts', to='courses.course')),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_posts', to='recipes.recipe')),
            ],
            options={
                'verbose_name': 'gallery post',
                'verbose_name_plural': 'gallery posts',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(storage=infrastructure.storage.base.get_media_storage, upload_to=apps.gallery.models.image.gallery_image_upload_to)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='gallery.gallerypost')),
            ],
            options={
                'verbose_name': 'gallery image',
                'verbose_name_plural': 'gallery images',
                'ordering': ('position', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='gallerypost',
            index=models.Index(fields=['status', '-created_at'], name='gallery_feed_idx'),
        ),
        migrations.AddIndex(
            model_name='gallerypost',
            index=models.Index(fields=['author', '-created_at'], name='gallery_author_idx'),
        ),
        migrations.AddIndex(
            model_name='galleryimage',
            index=models.Index(fields=['post', 'position'], name='gallery_image_order_idx'),
        ),
    ]
