# Generated by Django 5.2.17 on 2026-08-07 05:09

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(allow_unicode=True, help_text='Stable identifier used in URLs and filter parameters.', max_length=80, unique=True)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('icon', models.CharField(blank=True, help_text='Frontend icon key or emoji.', max_length=40)),
                ('display_order', models.PositiveSmallIntegerField(default=0, help_text='Lower values sort first.')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive categories stay assigned but are hidden from listings.')),
            ],
            options={
                'verbose_name': 'recipe category',
                'verbose_name_plural': 'recipe categories',
                'ordering': ('display_order', 'name'),
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('slug'), name='recipe_categories_slug_ci_unique')],
            },
        ),
    ]
