# Generated by Django 5.2.17 on 2026-08-10 09:27

import apps.recipe_categories.models.category
import infrastructure.storage.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_categories', '0003_deactivate_hard_to_classify_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipecategory',
            name='image',
            field=models.ImageField(blank=True, help_text='Tile photo shown on the home page and category boxes.', storage=infrastructure.storage.base.get_media_storage, upload_to=apps.recipe_categories.models.category.category_image_upload_to),
        ),
    ]
