# Generated by Django 5.2.17 on 2026-08-07 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='quiz',
            field=models.ForeignKey(blank=True, help_text='An optional quiz for this lesson — a reference only (Phase 4); quiz logic stays entirely in the quizzes app.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='quizzes.quiz'),
        ),
    ]
