# Generated by Django 5.2.17 on 2026-08-07 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_lesson_quiz'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LessonProgress',
        ),
    ]
