# Generated by Django 5.2.17 on 2026-08-07 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('recipes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True, max_length=2000)),
                ('status', models.CharField(choices=[('active', 'Active'), ('hidden', 'Hidden by moderation'), ('deleted', 'Deleted by the author')], db_index=True, default='active', max_length=20)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='courses.course')),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='recipes.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'review',
                'verbose_name_plural': 'reviews',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['recipe', 'status', '-created_at'], name='reviews_recipe_idx'), models.Index(fields=['course', 'status', '-created_at'], name='reviews_course_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('course__isnull', True), ('recipe__isnull', False)), models.Q(('course__isnull', False), ('recipe__isnull', True)), _connector='OR'), name='reviews_exactly_one_target'), models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='reviews_rating_range'), models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('user', 'recipe'), name='reviews_one_active_per_recipe'), models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('user', 'course'), name='reviews_one_active_per_course')],
            },
        ),
    ]
