# Generated by Django 5.2.17 on 2026-08-07 05:09

import apps.recipes.models.image
import apps.recipes.models.recipe
import apps.recipes.models.step
import django.db.models.deletion
import django.db.models.functions.text
import infrastructure.storage.base
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipe_categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(allow_unicode=True, help_text='Frozen once the recipe is first published.', max_length=180, unique=True)),
                ('summary', models.CharField(blank=True, help_text='One-line description shown on cards and in search results.', max_length=300)),
                ('description', models.TextField(blank=True)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('expert', 'Expert')], default='easy', max_length=20)),
                ('prep_minutes', models.PositiveIntegerField(default=0)),
                ('cook_minutes', models.PositiveIntegerField(default=0)),
                ('total_minutes', models.PositiveIntegerField(db_index=True, default=0, help_text='Derived from prep + cook by the service. Stored so that sorting and filtering by total time use an index instead of an expression.')),
                ('servings', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('visibility', models.CharField(choices=[('public', 'Anyone'), ('unlisted', 'Anyone with the link'), ('private', 'Only me')], db_index=True, default='public', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('cover_image', models.ImageField(blank=True, storage=infrastructure.storage.base.get_media_storage, upload_to=apps.recipes.models.recipe.cover_image_upload_to)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(blank=True, related_name='recipes', to='recipe_categories.recipecategory')),
            ],
            options={
                'verbose_name': 'recipe',
                'verbose_name_plural': 'recipes',
                'ordering': ('-published_at', '-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='nutrition', serialize=False, to='recipes.recipe')),
                ('basis', models.CharField(choices=[('per_serving', 'Per serving'), ('per_100g', 'Per 100 g')], default='per_serving', max_length=20)),
                ('source', models.CharField(choices=[('manual', 'Entered by the author'), ('estimated', 'Estimated automatically'), ('verified', 'Verified')], default='manual', help_text="Phase 2 only ever writes 'manual'.", max_length=20)),
                ('calculated_at', models.DateTimeField(blank=True, help_text='Set by the future estimator; unused in Phase 2.', null=True)),
                ('serving_size_grams', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('calories_kcal', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('protein_g', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('carbohydrate_g', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('sugar_g', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('fat_g', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('saturated_fat_g', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('fiber_g', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('sodium_mg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('cholesterol_mg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
            ],
            options={
                'verbose_name': 'nutrition',
                'verbose_name_plural': 'nutrition',
            },
        ),
        migrations.CreateModel(
            name='RecipeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(storage=infrastructure.storage.base.get_media_storage, upload_to=apps.recipes.models.image.recipe_image_upload_to)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='recipes.recipe')),
            ],
            options={
                'verbose_name': 'recipe image',
                'verbose_name_plural': 'recipe images',
                'ordering': ('position', 'id'),
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Exactly as the author typed it.', max_length=120)),
                ('normalized_name', models.CharField(db_index=True, help_text="NFC-normalised, casefolded, whitespace-collapsed form. Powers 'recipes containing X' as an indexed lookup and de-duplicates lines within a recipe.", max_length=120)),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, help_text="Null means an unmeasured amount, such as 'to taste'.", max_digits=7, null=True)),
                ('unit', models.CharField(blank=True, choices=[('g', 'g'), ('kg', 'kg'), ('ml', 'ml'), ('l', 'l'), ('tsp', 'tsp'), ('tbsp', 'tbsp'), ('cup', 'cup'), ('piece', 'piece'), ('pinch', 'pinch'), ('slice', 'slice'), ('to_taste', 'to taste')], default='g', max_length=20)),
                ('note', models.CharField(blank=True, help_text="Preparation note, for example 'sifted' or 'room temperature'.", max_length=120)),
                ('group', models.CharField(blank=True, help_text="Section heading, for example 'For the ganache'.", max_length=60)),
                ('is_optional', models.BooleanField(default=False)),
                ('position', models.PositiveSmallIntegerField(default=0, help_text='Server-assigned from the submitted array order.')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes.recipe')),
            ],
            options={
                'verbose_name': 'recipe ingredient',
                'verbose_name_plural': 'recipe ingredients',
                'ordering': ('group', 'position', 'id'),
            },
        ),
        migrations.CreateModel(
            name='RecipeStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveSmallIntegerField(default=1)),
                ('body', models.TextField(max_length=2000)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, help_text='Optional per-step timer.', null=True)),
                ('image', models.ImageField(blank=True, storage=infrastructure.storage.base.get_media_storage, upload_to=apps.recipes.models.step.step_image_upload_to)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='recipes.recipe')),
            ],
            options={
                'verbose_name': 'recipe step',
                'verbose_name_plural': 'recipe steps',
                'ordering': ('position', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['status', 'visibility', '-published_at'], name='recipes_listing_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['author', 'status'], name='recipes_author_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('slug'), name='recipes_recipe_slug_ci_unique'),
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.CheckConstraint(condition=models.Q(('total_minutes__lte', 10080)), name='recipes_recipe_total_minutes_max'),
        ),
        migrations.AddIndex(
            model_name='recipeimage',
            index=models.Index(fields=['recipe', 'position'], name='recipes_image_order_idx'),
        ),
        migrations.AddIndex(
            model_name='recipeingredient',
            index=models.Index(fields=['recipe', 'position'], name='recipes_ingredient_order_idx'),
        ),
        migrations.AddIndex(
            model_name='recipestep',
            index=models.Index(fields=['recipe', 'position'], name='recipes_step_order_idx'),
        ),
    ]
