# Generated by Django 5.2.17 on 2026-08-11 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_event_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='event_type',
            field=models.CharField(choices=[('review_received', 'Review received'), ('course_enrollment', 'New course enrollment'), ('achievement_earned', 'Achievement earned'), ('qa_answer_received', 'Your question got an answer'), ('qa_answer_accepted', 'Your answer was accepted'), ('announcement', 'Platform announcement')], max_length=30),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='event_type',
            field=models.CharField(choices=[('review_received', 'Review received'), ('course_enrollment', 'New course enrollment'), ('achievement_earned', 'Achievement earned'), ('qa_answer_received', 'Your question got an answer'), ('qa_answer_accepted', 'Your answer was accepted'), ('announcement', 'Platform announcement')], max_length=30),
        ),
    ]
