# Generated by Django 5.2.17 on 2026-08-11 03:42

import apps.notifications.models.campaign
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_event_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='cta_text',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='notification',
            name='icon',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.CreateModel(
            name='NotificationCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(default='custom', max_length=40)),
                ('icon', models.CharField(blank=True, max_length=16)),
                ('title', models.CharField(max_length=200)),
                ('body', models.CharField(blank=True, max_length=500)),
                ('cta_text', models.CharField(blank=True, max_length=60)),
                ('link', models.CharField(blank=True, max_length=300)),
                ('audience', models.JSONField(default=apps.notifications.models.campaign.default_audience)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sent', 'Sent'), ('canceled', 'Canceled')], default='draft', max_length=12)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('recipients_count', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notification campaign',
                'verbose_name_plural': 'notification campaigns',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='notifications.notificationcampaign'),
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(default='custom', max_length=40)),
                ('icon', models.CharField(blank=True, max_length=16)),
                ('title', models.CharField(max_length=200)),
                ('body', models.CharField(blank=True, max_length=500)),
                ('cta_text', models.CharField(blank=True, max_length=60)),
                ('link', models.CharField(blank=True, max_length=300)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notification template',
                'verbose_name_plural': 'notification templates',
                'ordering': ('is_archived', 'name', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='notificationcampaign',
            index=models.Index(fields=['status', '-created_at'], name='campaign_status_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationcampaign',
            index=models.Index(fields=['status', 'scheduled_at'], name='campaign_due_idx'),
        ),
    ]
